# Generated by Django 2.2.5 on 2020-06-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=13)),
                ('To', models.CharField(max_length=13)),
                ('Text', models.CharField(blank=True, max_length=1024)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
