# Generated by Django 2.2.5 on 2020-06-28 15:36

import Messenger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date_time',
            field=models.DateTimeField(default=Messenger.models.return_date_time),
        ),
    ]
