# Generated by Django 3.0.7 on 2020-07-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0002_messages_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
