# Generated by Django 3.0.7 on 2020-07-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0003_photobank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoBank',
        ),
    ]
